version: "2"

checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

plugins:
  sonar-java:
    enabled: true

  pmd:
    enabled: true
    config:
      rules:
        - "java-basic"
        - "java-strings"
        - "java-empty"
        - "java-design"
        - "java-logging-java"
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - java

exclude_patterns:
  - "src/test/"
  - "*/src/test/"
  - "*.html"
  - ".*"
  - "*.yml"
  - "*/src/main/webapp/"
  - "/src/main/webapp/*"
  - "*.xml"
  - "*.js"
  - "*.map"