stages:
  - test
  - badges
  - deploy

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

variables:
  DOCKER_TLS_CERTDIR: ""
  QUALITY_BASE_REPO: https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.widas.de/widas/codequality.git
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

image: docker:git

codecoverage:
    image: thyrlian/android-sdk
    stage: test
    variables:
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
    script: 
      - export GRADLE_USER_HOME=`pwd`/.gradle
      - ./gradlew build --exclude-task test --continue || BUILDFAILED=true #Continue with the nex step even on test failures
      - ./gradlew test --continue || TESTFAILED=true #Continue with the nex step even on test failures
      - ./gradlew jacocoFullReport #! can only be executed after the build & test stage are finished
      - cat build/reports/jacoco/jacocoFullReport/html/index.html
    artifacts:
        paths: [build/reports/jacoco/jacocoFullReport/html/*]
        

dependency_scanning:
  image: docker:stable
  stage: test
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
    paths: [gl-dependency-scanning-report.json]


code_quality_json:
  stage: test
  allow_failure: true
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    CODE_QUALITY_IMAGE: "registry.gitlab.com/gitlab-org/ci-cd/codequality:latest"
  script:
    - docker pull "$CODE_QUALITY_IMAGE"
    - git clone ${QUALITY_BASE_REPO}
    - cp codequality/conf/codeclimate/rules/js/.codeclimate.yml .
    - rm -rf codequality
    - docker run
      --env SOURCE_CODE="$PWD"
      --env CODECLIMATE_CODE="$PWD/app"
      --volume /tmp/cc:/tmp/cc
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      "$CODE_QUALITY_IMAGE" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths: [gl-code-quality-report.json]
  dependencies: []


code_quality_html:
  stage: test
  allow_failure: true
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    CONTAINERID: ""
  script:
    - docker pull codeclimate/codeclimate
    # Clone the .codeclimate.yml from the code quality base repo
    - git clone ${QUALITY_BASE_REPO}
    - cp codequality/conf/codeclimate/rules/js/.codeclimate.yml .
    - rm -rf codequality
    # Install the code climate engines
    - docker run
      --env SOURCE_CODE="$PWD"
      --env CODECLIMATE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      --volume /tmp/cc:/tmp/cc
      -d codeclimate/codeclimate engines:install > /dev/null
    # Get container ID
    # Run code climate
    - docker run
      --env SOURCE_CODE="$PWD"
      --env CODECLIMATE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      --volume /tmp/cc:/tmp/cc
      codeclimate/codeclimate analyze /code -f html > codeclimate.html
  artifacts:
    paths: [codeclimate.html]
  dependencies: []

create_codequality_badges:
  image: python:3-stretch
  stage: badges
  dependencies:
    - code_quality_json
    - codecoverage
  script:
  # Parse the codeclimate report for badges
    - git clone ${QUALITY_BASE_REPO}
    - cp codequality/src/calculate_codeclimate_metrics.py .
    - rm -rf codequality
    - python3 calculate_codeclimate_metrics.py gl-code-quality-report.json

    # Parse the code coverage for badges
    - pwd
    - ls -lah
    - cp build/reports/jacoco/jacocoFullReport/html/index.html .
    - git clone ${QUALITY_BASE_REPO}
    - cp codequality/src/count_lines_java_code.py .
    - rm -rf codequality
    - python3 count_lines_java_code.py

    # Using anybadge to create the badges
    - pip install anybadge
    # Setup the color ranges for the badges
    - export BADGE_COLOR_RANGE_MINOR="10=green 20=yellow 50=orange 100=red 200=brightred"
    - export BADGE_COLOR_RANGE_MAJOR="1=green 10=yellow 40=orange 100=red 150=brightred"
    - export BADGE_COLOR_RANGE_CRITICAL="1=green 3=yellow 5=orange 10=red 20=brightred"
    - export BADGE_COLOR_RANGE_FIXME="1=green 10=yellow 30=orange 50=red 100=brightred"
    - export BADGE_COLOR_RANGE_TOTAL="1=green 50=yellow 100=orange 200=red 300=brightred"

    - export DATE=$(cat date.txt)
    - anybadge -l sw_quality -v "$DATE" -f sw_quality.svg --color=green

    - export TOTAL_ISSUES=$(cat total_issues.txt)
    - anybadge -l total_issues -v $TOTAL_ISSUES -m "%d" -u -f total_issues.svg $BADGE_COLOR_RANGE_TOTAL

    - export CRITICAL_ISSUES=$(cat critical_issues.txt)
    - anybadge -l critical_issues -v $CRITICAL_ISSUES -m "%d" -u -f critical_issues.svg $BADGE_COLOR_RANGE_CRITICAL

    - export BLOCKER_ISSUES=$(cat blocker_issues.txt)
    - anybadge -l blocker_issues -v $BLOCKER_ISSUES -m "%d" -u -f blocker_issues.svg $BADGE_COLOR_RANGE_CRITICAL

    - export MAJOR_ISSUES=$(cat major_issues.txt)
    - anybadge -l major_issues -v $MAJOR_ISSUES -m "%d" -u -f major_issues.svg $BADGE_COLOR_RANGE_MAJOR

    - export MINOR_ISSUES=$(cat minor_issues.txt)
    - anybadge -l minor_issues -v $MINOR_ISSUES -m "%d" -u -f minor_issues.svg $BADGE_COLOR_RANGE_MINOR

    - export FIXME_ISSUES=$(cat fixme_issues.txt)
    - anybadge -l fixmes -v $FIXME_ISSUES -m "%d" -u -f fixme_issues.svg $BADGE_COLOR_RANGE_FIXME

    - export DUPLICATION_ISSUES=$(cat duplication_issues.txt)
    - anybadge -l duplications -v $DUPLICATION_ISSUES -m "%d" -u -f duplication_issues.svg $BADGE_COLOR_RANGE_CRITICAL
    
    - export LOC=$(cat loc.txt)
    - anybadge -l LoC -v $LOC -f loc.svg --color=green

    - export CLASSES=$(cat classes.txt)
    - anybadge -l Classes -v $CLASSES -f classes.svg --color=green

    # Export the created .svg's to the public directory
    - mkdir public
    - mv *.svg public
  artifacts:
    paths:
      - public/*.svg


pages:
  image: maven:3-jdk-8
  stage: deploy
  dependencies:
    - code_quality_html
    - code_quality_json
    - create_codequality_badges
    - codecoverage
  script:
    - mv codeclimate.html public/codeclimate.html
    - mkdir -p public/jacoco/
    - mv build/reports/jacoco/jacocoFullReport/* public/jacoco/
    - mv gl-code-quality-report.json public/gl-code-quality-report.json
  artifacts:
    paths:
      - public
