include:
  - project: 'widas/codequality'
    ref: code-coverage-failure-allow 
    file: 'ci_templates/android.gitlab-ci.yml'
  - template: Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - badges
  - deploy
