include:
  - project: 'widas/codequality'
    ref: code-coverage-failure-allow 
    file: 'ci_templates/android.gitlab-ci.yml'
  - template: Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - badges
  - deploy

code_quality_json:
  stage: test
  allow_failure: true
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    CODE_QUALITY_IMAGE: "registry.gitlab.com/gitlab-org/ci-cd/codequality:latest"
  script:
    - docker pull "$CODE_QUALITY_IMAGE"
    # Clone the .codeclimate.yml from the code quality base repo
    - git clone ${QUALITY_BASE_REPO}
    - cp codequality/conf/codeclimate/rules/java/.codeclimate.yml .
    - rm -rf codequality
    # Run the codeclimate image from gitlab
    - docker run
      --env SOURCE_CODE="$PWD"
      --env CODECLIMATE_CODE="$PWD/app"
      --volume /tmp/cc:/tmp/cc
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      "$CODE_QUALITY_IMAGE" /code
    # added for temp release
    - touch gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths: [gl-code-quality-report.json]
  dependencies: []
