language: android
env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a
android:
  components:
    - build-tools-27.1.1
    - build-tools-27.0.3
    - $ANDROID_TARGET
    - sys-img-armeabi-v7a-$ANDROID_TARGET

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-googletv-license-.+'

before_script:
 # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &



before_install:
- yes | sdkmanager "platforms;android-27"



script: ./gradlew jacocoTestReport

after_success:
 - codecov
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN





