package com.example.cidaasv2.Helper.Enums;

/**
 * Created by widasrnarayanan on 16/1/18.
 */

public class WebAuthErrorCode {

  public static final int DEFAULT=10000;
  public static final int FILE_NOT_FOUND=10001;
  public static final int NO_CONTENT_IN_FILE=10002;
  public static final int PROPERTY_MISSING=10003;
  public static final int REQUEST_ID_SERVICE_FAILURE=10004;
  public static final int EMPTY_REQUEST_ID_SERVICE=10005;
  public static final int EMPTY_LOGIN_URL = 10006;
  public static final int EMPTY_REDIRECT_URL = 10007;
  public static final int EMPTY_DELEGATE = 10008;
  public static final int USER_CANCELLED_LOGIN = 10009;
  public static final int CODE_NOT_FOUND = 10010;
  public static final int ACCESSTOKEN_SERVICE_FAILURE = 10011;
  public static final int EMPTY_LOGIN_URL_SERVICE = 10012;
  public static final int ERROR_JSON_PARSING = 10013;
  public static final int USER_INFO_SERVICE_FAILURE = 10014;
  public static final int EMPTY_CALLBACK = 10015;
  public static final int NO_USER_FOUND = 10016;
  public static final int REFRESH_TOKEN_SERVICE_FAILURE = 10017;
  public static final int TENANT_INFO_FAILURE = 10018;
  public static final int CLIENT_INFO_FAILURE = 10019;
  public static final int REQUEST_ID_MISSING = 10020;
  public static final int LOGINWITH_CREDENTIALS_FAILURE = 10021;
  public static final int REGISTRATION_SETUP_FAILURE = 10022;
  public static final int CONSENT_URL_FAILURE = 10023;
  public static final int CONSENT_STRING_FAILURE = 10024;
  public static final int ACCEPT_CONSENT_FAILURE = 10025;
  public static final int MFA_LIST_FAILURE = 10026;
  public static final int INITIATE_EMAIL_MFA_FAILURE = 10027;
  public static final int AUTHENTICATE_EMAIL_MFA_FAILURE = 10028;
  public static final int INITIATE_RESET_PASSWORD_FAILURE = 10029;
  public static final int RESET_PASSWORD_VALIDATE_CODE_FAILURE = 10030;
  public static final int RESET_NEWPASSWORD_FAILURE = 10031;
  public static final int CHANGE_PASSWORD_FAILURE = 10032;
  public static final int INITIATE_SMS_MFA_FAILURE = 10033;
  public static final int AUTHENTICATE_SMS_MFA_FAILURE = 10034;
  public static final int INITIATE_IVR_MFA_FAILURE = 10035;
  public static final int AUTHENTICATE_IVR_MFA_FAILURE = 10036;
  public static final int INITIATE_BACKUPCODE_MFA_FAILURE = 10037;
  public static final int AUTHENTICATE_BACKUPCODE_MFA_FAILURE = 10038;
  public static final int RESUME_LOGIN_FAILURE = 10039;
  public static final int INITIATE_FACE_MFA_FAILURE = 10040;
  public static final int AUTHENTICATE_FACE_MFA_FAILURE = 10041;
  public static final int INITIATE_FINGERPRINT_MFA_FAILURE = 10042;
  public static final int AUTHENTICATE_FINGERPRINT_MFA_FAILURE = 10043;
  public static final int INITIATE_VOICE_MFA_FAILURE = 10044;
  public static final int AUTHENTICATE_VOICE_MFA_FAILURE = 10045;
  public static final int INITIATE_PATTERN_MFA_FAILURE = 10046;
  public static final int AUTHENTICATE_PATTERN_MFA_FAILURE = 10047;
  public static final int INITIATE_SMARTPUSH_MFA_FAILURE = 10048;
  public static final int AUTHENTICATE_SMARTPUSH_MFA_FAILURE = 10049;
  public static final int INITIATE_TOTP_MFA_FAILURE = 10050;
  public static final int AUTHENTICATE_TOTP_MFA_FAILURE = 10051;
  public static final int INITIATE_FIDO_MFA_FAILURE = 10052;
  public static final int AUTHENTICATE_FIDO_MFA_FAILURE = 10053;
  public static final int RESUME_CONSENT_FAILURE = 10054;
  public static final int SETUP_SMS_MFA_FAILURE = 10055;
  public static final int ENROLL_SMS_MFA_FAILURE = 10056;
  public static final int SETUP_IVR_MFA_FAILURE = 10057;
  public static final int ENROLL_IVR_MFA_FAILURE = 10058;
  public static final int SETUP_BACKUPCODE_MFA_FAILURE = 10059;
  public static final int ENROLL_BACKUPCODE_MFA_FAILURE = 10060;
  public static final int SETUP_FACE_MFA_FAILURE = 10061;
  public static final int ENROLL_FACE_MFA_FAILURE = 10062;
  public static final int SETUP_FINGERPRINT_MFA_FAILURE = 10063;
  public static final int ENROLL_FINGERPRINT_MFA_FAILURE = 10064;
  public static final int SETUP_VOICE_MFA_FAILURE = 10065;
  public static final int ENROLL_VOICE_MFA_FAILURE = 10066;
  public static final int SETUP_PATTERN_MFA_FAILURE = 10067;
  public static final int ENROLL_PATTERN_MFA_FAILURE = 10068;
  public static final int SETUP_SMARTPUSH_MFA_FAILURE = 10069;
  public static final int ENROLL_SMARTPUSH_MFA_FAILURE = 10070;
  public static final int SETUP_TOTP_MFA_FAILURE = 10071;
  public static final int ENROLL_TOTP_MFA_FAILURE = 10072;
  public static final int SETUP_FIDO_MFA_FAILURE = 10073;
  public static final int ENROLL_FIDO_MFA_FAILURE = 10074;
  public static final int SETUP_EMAIL_MFA_FAILURE = 10075;
  public static final int ENROLL_EMAIL_MFA_FAILURE = 10076;
  public static final int INTERNAL_USER_PROFILE_FAILURE = 10077;
  public static final int INITIATE_ACCOUNT_VERIFICATION_FAILURE = 10078;
  public static final int VERIFY_ACCOUNT_VERIFICATION_FAILURE = 10079;
  public static final int DEVICE_VERIFICATION_FAILURE=10080;
  public static final int SCANNED_PATTERN_MFA_FAILURE = 10081;
  public static final int SCANNED_FACE_MFA_FAILURE = 10082;
  public static final int SCANNED_VOICE_MFA_FAILURE = 10083;
  public static final int SCANNED_TOTP_MFA_FAILURE = 10084;
  public static final int SCANNED_FINGERPRINT_MFA_FAILURE = 10085;
  public static final int SCANNED_SMARTPUSH_MFA_FAILURE = 10086;
  public static final int DEDUPLICATION_LIST_FAILURE = 10087;
  public static final int DEDUPLICATION_REGISTRATION_FAILURE = 10088;
  public static final int DEDUPLICATION_LOGIN_FAILURE = 10089;

}
